### ISSUE TITLE
error with StringVector

### ISSUE THREAD

**Issue by big-fish0** [hyperledger/iroha#1276]
```
 StringVector permissions = new StringVector();
 permissions.add("can_get_my_acc_ast_txs");
```
When i test `CreatorrRole` function,it returns an error
```
        Exception in thread "main" java.lang.UnsatisfiedLinkError: irohaJNI.new_StringVector__SWIG_1(J)J
        at irohaJNI.new_StringVector__SWIG_1(Native Method)
        at StringVector.<init>(StringVector.java:42)
        at test.main(test.java:9)
```

**Comment by big-fish0** [comment]
@l4l Thanks
