### ISSUE TITLE
error while running node sample

### ISSUE THREAD

**Issue by pradeeppadmarajaiah** [hyperledger/iroha#1421]
Error happens when running index.js. Not sure why it is pointing to different user directory. Please let me know, how to launch the sample

**LOGS**
pradeep@pradeep-VirtualBox:~/iroha/example/node$ node index.js 
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /home/stinger112/dev/soramitsu/iroha/shared_model/packages/javascript/lib/node-v57-linux-x64-glibc/irohanode.so: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pradeep/iroha/example/node/node_modules/iroha-lib/index.js:4:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
pradeep@pradeep-VirtualBox:~/iroha/example/node$

**Comment by laSinteZ** [comment]
You might try the latest version of our lib from npm - https://www.npmjs.com/package/iroha-lib/v/0.1.4, it is built with Emscripten and doesn't require binaries for every system. Also, you can try to build library on your own using http://iroha.readthedocs.io/en/latest/guides/libraries/nodejs.html

**Comment by stinger112** [comment]
Seems like version of iroha-lib in the example's package.json is outdated. Please do npm install iroha-lib@emscripten this is the latest version.

**Comment by l4l** [comment]
Seems resolved as long as there's no response
