### ISSUE TITLE
ERROR:java.lang.UnsatisfiedLinkError: jp.co.soramitsu.iroha.irohaJNI.new_ModelCrypto()J

### ISSUE THREAD

**Issue by big-fish0** [hyperledger/iroha#1526]
I added the code ,
```
static
  {
    try
    {
    	System.loadLibrary("ed25519");
    	System.loadLibrary("protobuf");
        System.loadLibrary("irohajava");
    }
    catch (UnsatisfiedLinkError e)
    {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
```
and i had added the java library path,but it logs that

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: jp.co.soramitsu.iroha.irohaJNI.new_ModelCrypto()J
	at jp.co.soramitsu.iroha.irohaJNI.new_ModelCrypto(Native Method)
	at jp.co.soramitsu.iroha.ModelCrypto.<init>(ModelCrypto.java:51)
	at TransactionExample.<clinit>(TransactionExample.java:59)
```

**Comment by Warchant** [comment]
What is the version of bindings? Provide commit pls.
