### ISSUE TITLE
[th:64][warning] CommandService Found transaction 2140b6ee2aa50fce44666cc4cb1e46836a0de39710c2e04c9454b3fec2d36ad1 in cache, ignoring

### ISSUE THREAD

**Issue by big-fish0** [hyperledger/iroha#1530]
I don't know the log will return any resluts.But in my application ,some transactions failed,and the `response.getTxStatus().name = STATELESS_VALIDATION_FAILED`

I use the same API to add assetQty,I use the code follow:
```
for (Integer i = 0; i < 100; i++) {
			
	try {
	  String hex = irohaService.cmdAddAssetQuantity("admin@test", "admin@test", "coin#test", "1.00");
	} catch (InvalidProtocolBufferException e) {
				e.printStackTrace();
	}
	   System.out.println(hex);
	}

```

**Comment by big-fish0** [comment]
And also sometimes logs that
```
七月 03, 2018 1:55:10 下午 io.grpc.internal.ManagedChannelImpl$ManagedChannelReference cleanQueue
严重: *~*~*~ Channel io.grpc.internal.ManagedChannelImpl-433 for target 192.168.1.211:50051 was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and awaitTermination().
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelImpl$ManagedChannelReference.<init>(ManagedChannelImpl.java:1065)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:485)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:349)
	at com.bjb.service.IrohaTransaction.sendCmd2Iroha(IrohaTransaction.java:299)
	at com.bjb.service.IrohaService.cmdIsSuccess(IrohaService.java:199)
	at com.bjb.service.IrohaService.cmdAddAssetQuantity(IrohaService.java:337)
	at com.bjb.service.IrohaService$$FastClassBySpringCGLIB$$7bde04b0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at com.bjb.service.IrohaService$$EnhancerBySpringCGLIB$$1b39e440.cmdAddAssetQuantity(<generated>)
	at com.bjb.controller.TestController.addAsset(TestController.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:860)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by big-fish0** [comment]
I guess the hash value is related to the time when the transaction was generated.Was  time accuracy  accurate to milliseconds?

**Comment by l4l** [comment]
@big-fish0 
get the container id via `docker ps` (maybe you need to add -a also)
then get the logs via `docker logs -f <id>`

**Comment by big-fish0** [comment]
```
root@iroha:~# docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                                                NAMES
232cae951df5        hyperledger/iroha:develop-build   "/bin/bash"              3 hours ago         Up 3 hours          0.0.0.0:20000->20000/tcp, 0.0.0.0:50051->50051/tcp   iroha0_node_1
e6a075bc2aa7        postgres:9.5                      "docker-entrypoint.s…"   3 hours ago         Up 3 hours          0.0.0.0:5432->5432/tcp                               iroha0_postgres_1
```
`root@iroha:~# docker logs -f 232cae951df5`

I doesn't return any log,it was null

**Comment by neewy** [comment]
Seems that Iroha did not start. Which is really a bad sign, can you please tell when did you pull the image?

**Comment by big-fish0** [comment]
@neewy Yesterday(2018-07-03)

**Comment by big-fish0** [comment]
@l4l @neewy 
I have forgotten to tell you, I had started 10 threads to run this code
```
for (Integer i = 0; i < 100; i++) {
			
	try {
	  String hex = irohaService.cmdAddAssetQuantity("admin@test", "admin@test", "coin#test", "1.00");
	} catch (InvalidProtocolBufferException e) {
	 e.printStackTrace();
	}
	   System.out.println(hex);
	}
```

I think it was the parameter  time causes this bug.Today ,I run follow code ,i got 199 bugs like `CommandService Found transaction xxxx in cache, ignoring `

```
package com.iroha.test;
import java.io.IOException;
import java.math.BigInteger;
import java.nio.file.Files;
import java.nio.file.Paths;

import com.google.protobuf.ByteString;
import com.google.protobuf.Descriptors;
import com.google.protobuf.InvalidProtocolBufferException;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import iroha.protocol.BlockOuterClass;
import iroha.protocol.CommandServiceGrpc;
import iroha.protocol.Endpoint;
import iroha.protocol.Queries;
import iroha.protocol.QueryServiceGrpc;
import iroha.protocol.Responses;
import jp.co.soramitsu.iroha.ByteVector;
import jp.co.soramitsu.iroha.Keypair;
import jp.co.soramitsu.iroha.ModelCrypto;
import jp.co.soramitsu.iroha.ModelProtoQuery;
import jp.co.soramitsu.iroha.ModelProtoTransaction;
import jp.co.soramitsu.iroha.ModelQueryBuilder;
import jp.co.soramitsu.iroha.ModelTransactionBuilder;
import jp.co.soramitsu.iroha.UnsignedQuery;
import jp.co.soramitsu.iroha.UnsignedTx;

class TransactionExample
{
	static {
        try {
        	System.loadLibrary("ed25519");
        	System.loadLibrary("protobuf");
            System.loadLibrary("irohajava");
        } catch (UnsatisfiedLinkError e) {
            System.err.println("Native code library failed to load. \n" + e);
            System.exit(1);
        }
    }
  
  private static ModelCrypto crypto = new ModelCrypto();
  private static ModelTransactionBuilder txBuilder = new ModelTransactionBuilder();
  private static ModelQueryBuilder queryBuilder = new ModelQueryBuilder();
  
  public static byte[] toByteArray(ByteVector blob)
  {
    byte[] bs = new byte[(int)blob.size()];
    for (int i = 0; i < blob.size(); i++) {
      bs[i] = ((byte)blob.get(i));
    }
    return bs;
  }
  
  public static String readKeyFromFile(String path)
  {
    try
    {
      return new String(Files.readAllBytes(Paths.get(path, new String[0])));
    }
    catch (IOException e)
    {
      System.err.println("Unable to read key files.\n " + e);
      System.exit(1);
    }
    return "";
  }
  
  public static void main(String[] args)
  {
    Keypair keys = crypto.convertFromExisting(readKeyFromFile("./admin@test.pub"), 
      readKeyFromFile("./admin@test.priv"));
    
    
    String creator = "admin@test";
   ###  long currentTime = System.currentTimeMillis();
    
    for (int i = 0; i < 200; i++) {
		
    	 
	    UnsignedTx utx = txBuilder.creatorAccountId(creator).createdTime(BigInteger.valueOf(currentTime)).addAssetQuantity(creator, "coin#test", "1.00").build();
	    
	    
	    ByteVector txblob = new ModelProtoTransaction(utx).signAndAddSignature(keys).finish().blob();
	    
	
	    byte[] bs = toByteArray(txblob);
	    
	
	    BlockOuterClass.Transaction protoTx = null;
	    try
	    {
	      protoTx = BlockOuterClass.Transaction.parseFrom(bs);
	    }
	    catch (InvalidProtocolBufferException e)
	    {
	      System.err.println("Exception while converting byte array to protobuf:" + e.getMessage());
	      System.exit(1);
	    }
	    ManagedChannel channel = ManagedChannelBuilder.forAddress("192.168.1.211", 50051).usePlaintext(true).build();
	    CommandServiceGrpc.CommandServiceBlockingStub stub = CommandServiceGrpc.newBlockingStub(channel);
	    stub.torii(protoTx);
	   /* try
	    {
	      Thread.sleep(5000L);
	    }
	    catch (InterruptedException ex)
	    {
	      Thread.currentThread().interrupt();
	    }*/
	//    System.out.println("Hash of the transaction: " + utx.hash().hex());
    }

  }
}
```

**Comment by l4l** [comment]
The problem is here: `createdTime(BigInteger.valueOf(currentTime))`
You have exactly same transactions that are going to the irohad, and after the first one it's been put in the cache. The rest (199 out of 200) are considered as duplicate.

**Comment by big-fish0** [comment]
@l4l 
Yes, it is. But if we start multiple threads to do the same thing example,addassetqty, it also will produces the same error like:`CommandService Found transaction xxxx in cache, ignoring`

**Comment by big-fish0** [comment]
For example, I had tried run 10 threads x 10 loop on the same pc, this time occured 6 times :
CommandService Found transaction xxxx in cache, ignoring

```
package com.iroha.test;

import java.io.IOException;
import java.math.BigInteger;
import java.nio.file.Files;
import java.nio.file.Paths;

import com.google.protobuf.InvalidProtocolBufferException;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import iroha.protocol.BlockOuterClass;
import iroha.protocol.CommandServiceGrpc;
import jp.co.soramitsu.iroha.ByteVector;
import jp.co.soramitsu.iroha.Keypair;
import jp.co.soramitsu.iroha.ModelCrypto;
import jp.co.soramitsu.iroha.ModelProtoTransaction;
import jp.co.soramitsu.iroha.ModelTransactionBuilder;
import jp.co.soramitsu.iroha.UnsignedTx;

public class Test {

	static {
        try {
        	System.loadLibrary("ed25519");
        	System.loadLibrary("protobuf");
            System.loadLibrary("irohajava");
        } catch (UnsatisfiedLinkError e) {
            System.err.println("Native code library failed to load. \n" + e);
            System.exit(1);
        }
    }
	
	public static void main(String[] args) {
		for (int i = 0; i < 10; i++) {
			irohaThread it = new irohaThread();
			it.start();
		}

	}

}


class irohaThread extends Thread{
	
	static long preTime = 0;
	static int count = 0;
	private static ModelCrypto crypto = new ModelCrypto();
	private static ModelTransactionBuilder txBuilder = new ModelTransactionBuilder();
	  
	public static byte[] toByteArray(ByteVector blob)
	{
	    byte[] bs = new byte[(int)blob.size()];
	    for (int i = 0; i < blob.size(); i++) {
	    	bs[i] = ((byte)blob.get(i));
	    }
	    return bs;
	}
	  
	public static String readKeyFromFile(String path)
	{
	    try
	    {
	    	return new String(Files.readAllBytes(Paths.get(path, new String[0])));
	    }
	    catch (IOException e)
	    {
	    	System.err.println("Unable to read key files.\n " + e);
	    	System.exit(1);
	    }
	    return "";
	}
	
	Keypair keys = crypto.convertFromExisting(readKeyFromFile("./admin@test.pub"),readKeyFromFile("./admin@test.priv"));
    String creator = "admin@test";
    
	
	@Override
	public void run() {
		for (int i = 0; i < 10; i++) {
			
			long currentTime = System.currentTimeMillis();
			System.out.println(currentTime);
		    UnsignedTx utx = txBuilder.creatorAccountId(creator).createdTime(BigInteger.valueOf(currentTime)).addAssetQuantity(creator, "coin#test", "1.00").build();
		    
		    
		    ByteVector txblob = new ModelProtoTransaction(utx).signAndAddSignature(keys).finish().blob();
		    
		
		    byte[] bs = toByteArray(txblob);
		    
		
		    BlockOuterClass.Transaction protoTx = null;
		    try
		    {
		      protoTx = BlockOuterClass.Transaction.parseFrom(bs);
		    }
		    catch (InvalidProtocolBufferException e)
		    {
		      System.err.println("Exception while converting byte array to protobuf:" + e.getMessage());
		      System.exit(1);
		    }
		    ManagedChannel channel = ManagedChannelBuilder.forAddress("192.168.1.211", 50051).usePlaintext(true).build();
		    CommandServiceGrpc.CommandServiceBlockingStub stub = CommandServiceGrpc.newBlockingStub(channel);
		    stub.torii(protoTx);
		    System.out.println("done");
	    }
	}
}
```

**Comment by l4l** [comment]
Since cache isn't synchronize (e.g after putting a value can be delayed by verification time), it's possible to happen. The proper behavior should lead to the accepting of the first one (considering it stateful valid), and the rest should be rejected (e.g stateful fail or found in cache).
Could you confirm that it's not an issue now?

**Comment by big-fish0** [comment]
It is indeed a problem now, in practical applications, this problem may occur if multiple users request the same interface.

**Comment by l4l** [comment]
The point is, that the time mustn't be the same. And the second point is that users still have different account names.
These are the cases which change transaction binary representation, thus changes its hash. So in reality there's no such problem

**Comment by big-fish0** [comment]
@l4l 
Thanks.
