### ISSUE TITLE
http server segfault

### ISSUE THREAD

**Issue by l4l** [hyperledger/iroha#197]
Just send SIGINT to iroha-main and this will cause:

```
#0  0x00007ff6d93b4304 in free () from /usr/lib/libc.so.6
#1  0x00000000005aa210 in __gnu_cxx::new_allocator<grpc::ServerCompletionQueue*>::deallocate (this=0x926e70 <connection::builder+80>, __p=0x100000001)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.3.1/../../../../include/c++/6.3.1/ext/new_allocator.h:110
#2  0x00000000005aa1e0 in std::allocator_traits<std::allocator<grpc::ServerCompletionQueue*> >::deallocate (__a=..., __p=0x100000001, __n=0xffffffffdfffffff)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.3.1/../../../../include/c++/6.3.1/bits/alloc_traits.h:442
#3  0x00000000005aa17b in std::_Vector_base<grpc::ServerCompletionQueue*, std::allocator<grpc::ServerCompletionQueue*> >::_M_deallocate (this=0x926e70 <connection::builder+80>, __p=0x100000001, __n=0xffffffffdfffffff)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.3.1/../../../../include/c++/6.3.1/bits/stl_vector.h:178
#4  0x00000000005aa0c9 in std::_Vector_base<grpc::ServerCompletionQueue*, std::allocator<grpc::ServerCompletionQueue*> >::~_Vector_base (this=0x926e70 <connection::builder+80>)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.3.1/../../../../include/c++/6.3.1/bits/stl_vector.h:160
#5  0x00000000005a9ab8 in std::vector<grpc::ServerCompletionQueue*, std::allocator<grpc::ServerCompletionQueue*> >::~vector (this=0x926e70 <connection::builder+80>)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.3.1/../../../../include/c++/6.3.1/bits/stl_vector.h:427
#6  0x00000000005a7a13 in grpc::ServerBuilder::~ServerBuilder (this=0x926e20 <connection::builder>) at /usr/local/include/grpc++/server_builder.h:61
#7  0x00007ff6d936e990 in __run_exit_handlers () from /usr/lib/libc.so.6
#8  0x00007ff6d936e9ea in exit () from /usr/lib/libc.so.6
#9  0x0000000000578f4e in Cappuccino::signal_utils::signal_handler (signal=0x2) at /home/kitsu/dev/Work/iroha/external/src/mizukisonoko_cappuccino/cappuccino.hpp:123
#10 <signal handler called>
#11 0x00007ff6da43f10d in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#12 0x00007ff6d9ca74cc in __gthread_cond_wait (__mutex=<optimized out>, __cond=<optimized out>) at /build/gcc-multilib/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:864
#13 std::condition_variable::wait (this=<optimized out>, __lock=...) at /build/gcc-multilib/src/gcc/libstdc++-v3/src/c++11/condition_variable.cc:53
#14 0x00007ff6d9fa9501 in grpc::Server::Wait() () from /usr/lib/libgrpc++.so.2
#15 0x00000000005a5df0 in connection::run () at /home/kitsu/dev/Work/iroha/core/infra/connection/connection_with_grpc.cpp:392
#16 0x000000000055cca5 in main () at /home/kitsu/dev/Work/iroha/peer/main.cpp:59
#17 0x00007ff6d9359291 in __libc_start_main () from /usr/lib/libc.so.6
#18 0x000000000055c89a in _start ()
```

I guess it can be due to the same reason as #190's grpc test

**Comment by Warchant** [comment]
closed by https://github.com/hyperledger/iroha/commit/a846c5a097320354601117c806af938ef63cd5c4

**Comment by takemiyamakoto** [comment]
This was reopened, but is it fixed in master from the latest merges?

**Comment by l4l** [comment]
Interesting, but can't reproduce so I guess that fixed
