### ISSUE TITLE
[documentation] Iroha 1 documentation build fails

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#3079]
### Description

Broken `m2r2` dependency stops the documentation builds.

Log:

```
python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
Running Sphinx v1.8.6
loading translations [en]... done
/home/docs/checkouts/readthedocs.org/user_builds/iroha/checkouts/main/docs/source/conf.py:125: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  common = yaml.load(stream)
/home/docs/checkouts/readthedocs.org/user_builds/iroha/checkouts/main/docs/source/conf.py:132: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  locale = yaml.load(stream)

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/iroha/envs/main/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
ModuleNotFoundError: No module named 'm2r2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/iroha/envs/main/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/iroha/envs/main/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/iroha/envs/main/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/iroha/envs/main/lib/python3.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension m2r2 (exception: No module named 'm2r2')

Extension error:
Could not import extension m2r2 (exception: No module named 'm2r2')
```

**Comment by 6r1d** [comment]
There were other issues I have detected on Read the Docs. I've refreshed all packages related to this issue now and will add another PR.
