### ISSUE TITLE
[BUG] Query store panic

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4085]
in the CI we've observed the following error:

```log
thread 'tokio-runtime-worker' panicked at 'Cannot block the current thread from within a runtime. This happens because a function attempted to block the current thread while the thread is being used to drive asynchronous tasks.', core/src/query/store.rs:232:14
```

Full log:
```log
---- integration::restart_peer::restarted_peer_should_have_the_same_asset_amount stdout ----
2023-11-27T07:45:47.865018Z  INFO iroha::samples: public_key=ed01207233BFC89DCBD68C19FDE6CE6158225298EC1131B6A130D1AEB454C1AB5183C0
2023-11-27T07:45:47.868385Z  INFO iroha::samples: public_key=ed01207233BFC89DCBD68C19FDE6CE6158225298EC1131B6A130D1AEB454C1AB5183C0
2023-11-27T07:45:47.931033Z  INFO test-peer{p2p_addr=127.0.0.1:10000 api_addr=127.0.0.1:10001}:init:start{listen_addr=127.0.0.1:10000}: iroha_p2p::network: Network bound to listener
2023-11-27T07:45:47.932976Z  INFO test-peer{p2p_addr=127.0.0.1:10000 api_addr=127.0.0.1:10001}:init:kura_init: iroha_core::kura: Kura init complete mode=Strict block_count=0
2023-11-27T07:45:47.933074Z  WARN test-peer{p2p_addr=127.0.0.1:10000 api_addr=127.0.0.1:10001}:init: iroha: Failed to load wsv from snapshot, creating empty wsv error=Failed reading/writing "./storage/snapshot.data" from disk
2023-11-27T07:45:47.935858Z  WARN test-peer{p2p_addr=127.0.0.1:10000 api_addr=127.0.0.1:10001}:init: iroha: Telemetry not started
2023-11-27T07:45:47.936030Z  INFO test-peer{p2p_addr=127.0.0.1:10000 api_addr=127.0.0.1:10001}:init: iroha_core::sumeragi: Sumeragi has finished loading blocks and setting up the WSV
2023-11-27T07:45:47.936556Z  INFO test-peer{p2p_addr=127.0.0.1:10000 api_addr=127.0.0.1:10001}: iroha: Starting Iroha as task
2023-11-27T07:45:48.238768Z  INFO request{method=GET path=/status version=HTTP/1.1 remote.addr=127.0.0.1:53374}: warp::filters::trace: processing request
2023-11-27T07:45:48.238838Z  INFO request{method=GET path=/status version=HTTP/1.1 remote.addr=127.0.0.1:53374}:request{method=GET path=/status version=HTTP/1.1 remote.addr=127.0.0.1:53374}: warp::filters::trace: processing request
2023-11-27T07:45:48.238987Z  WARN request{method=GET path=/status version=HTTP/1.1 remote.addr=127.0.0.1:53374}:request{method=GET path=/status version=HTTP/1.1 remote.addr=127.0.0.1:53374}: warp::filters::trace: unable to serve request (client error) status=404 error=Some(Rejection(NotFound))
2023-11-27T07:45:48.239396Z  INFO request{method=GET path=/status version=HTTP/1.1 remote.addr=127.0.0.1:53374}: warp::filters::trace: finished processing with success status=200
2023-11-27T07:45:48.440117Z  INFO consensus: iroha_core::sumeragi::main_loop: Genesis block created role=Leader block_hash=36526debce1b33b552096d1c04c25e6251dc7ec31e5e35b338e0e3d21099e711
2023-11-27T07:45:48.499705Z  INFO consensus: iroha_core::sumeragi::main_loop: Committing block addr=127.0.0.1:10000 role=Leader block_height=0 block_hash=36526debce1b33b552096d1c04c25e6251dc7ec31e5e35b338e0e3d21099e711
2023-11-27T07:45:49.240430Z  INFO request{method=GET path=/status version=HTTP/1.1 remote.addr=127.0.0.1:53382}: warp::filters::trace: processing request
2023-11-27T07:45:49.240498Z  INFO request{method=GET path=/status version=HTTP/1.1 remote.addr=127.0.0.1:53382}:request{method=GET path=/status version=HTTP/1.1 remote.addr=127.0.0.1:53382}: warp::filters::trace: processing request
2023-11-27T07:45:49.240638Z  WARN request{method=GET path=/status version=HTTP/1.1 remote.addr=127.0.0.1:53382}:request{method=GET path=/status version=HTTP/1.1 remote.addr=127.0.0.1:53382}: warp::filters::trace: unable to serve request (client error) status=404 error=Some(Rejection(NotFound))
2023-11-27T07:45:49.241172Z  INFO request{method=GET path=/status version=HTTP/1.1 remote.addr=127.0.0.1:53382}: warp::filters::trace: finished processing with success status=200
2023-11-27T07:45:49.243179Z  INFO request{method=GET path=/events version=HTTP/1.1 remote.addr=127.0.0.1:53392}: warp::filters::trace: processing request
2023-11-27T07:45:49.243244Z  INFO request{method=GET path=/events version=HTTP/1.1 remote.addr=127.0.0.1:53392}:request{method=GET path=/events version=HTTP/1.1 remote.addr=127.0.0.1:53392}: warp::filters::trace: processing request
2023-11-27T07:45:49.243497Z  INFO request{method=GET path=/events version=HTTP/1.1 remote.addr=127.0.0.1:53392}:request{method=GET path=/events version=HTTP/1.1 remote.addr=127.0.0.1:53392}: warp::filters::trace: finished processing with status status=101 error=None
2023-11-27T07:45:49.243576Z  INFO request{method=GET path=/events version=HTTP/1.1 remote.addr=127.0.0.1:53392}: warp::filters::trace: finished processing with status status=101 error=None
2023-11-27T07:45:49.244867Z  INFO request{method=POST path=/transaction version=HTTP/1.1 remote.addr=127.0.0.1:53404}: warp::filters::trace: processing request
2023-11-27T07:45:49.244927Z  INFO request{method=POST path=/transaction version=HTTP/1.1 remote.addr=127.0.0.1:53404}:request{method=POST path=/transaction version=HTTP/1.1 remote.addr=127.0.0.1:53404}: warp::filters::trace: processing request
2023-11-27T07:45:49.245061Z  WARN request{method=POST path=/transaction version=HTTP/1.1 remote.addr=127.0.0.1:53404}:request{method=POST path=/transaction version=HTTP/1.1 remote.addr=127.0.0.1:53404}: warp::filters::trace: unable to serve request (client error) status=404 error=Some(Rejection(NotFound))
2023-11-27T07:45:49.253310Z  INFO request{method=POST path=/transaction version=HTTP/1.1 remote.addr=127.0.0.1:53404}: warp::filters::trace: finished processing with success status=200
2023-11-27T07:45:50.850018Z  INFO consensus: iroha_core::sumeragi::main_loop: Creating block... addr=127.0.0.1:10000 txns=1
2023-11-27T07:45:50.852277Z  INFO consensus: iroha_core::sumeragi::main_loop: Committing block addr=127.0.0.1:10000 role=Leader block_height=1 block_hash=f48a37c120d0fa6d94ad64a86c19a6e1dff490b489b35162075107f67c3eebe1
2023-11-27T07:45:50.853428Z ERROR iroha_core::snapshot: Failed to create snapshot for wsv. error=Failed reading/writing "./storage/snapshot.tmp" from disk
2023-11-27T07:45:50.854428Z  INFO request{method=GET path=/events version=HTTP/1.1 remote.addr=127.0.0.1:53406}: warp::filters::trace: processing request
2023-11-27T07:45:50.854465Z  INFO request{method=GET path=/events version=HTTP/1.1 remote.addr=127.0.0.1:53406}:request{method=GET path=/events version=HTTP/1.1 remote.addr=127.0.0.1:53406}: warp::filters::trace: processing request
2023-11-27T07:45:50.854639Z  INFO request{method=GET path=/events version=HTTP/1.1 remote.addr=127.0.0.1:53406}:request{method=GET path=/events version=HTTP/1.1 remote.addr=127.0.0.1:53406}: warp::filters::trace: finished processing with status status=101 error=None
2023-11-27T07:45:50.854693Z  INFO request{method=GET path=/events version=HTTP/1.1 remote.addr=127.0.0.1:53406}: warp::filters::trace: finished processing with status status=101 error=None
2023-11-27T07:45:50.855326Z  INFO request{method=POST path=/transaction version=HTTP/1.1 remote.addr=127.0.0.1:53408}: warp::filters::trace: processing request
2023-11-27T07:45:50.855359Z  INFO request{method=POST path=/transaction version=HTTP/1.1 remote.addr=127.0.0.1:53408}:request{method=POST path=/transaction version=HTTP/1.1 remote.addr=127.0.0.1:53408}: warp::filters::trace: processing request
2023-11-27T07:45:50.855435Z  WARN request{method=POST path=/transaction version=HTTP/1.1 remote.addr=127.0.0.1:53408}:request{method=POST path=/transaction version=HTTP/1.1 remote.addr=127.0.0.1:53408}: warp::filters::trace: unable to serve request (client error) status=404 error=Some(Rejection(NotFound))
2023-11-27T07:45:50.862502Z  INFO request{method=POST path=/transaction version=HTTP/1.1 remote.addr=127.0.0.1:53408}: warp::filters::trace: finished processing with success status=200
2023-11-27T07:45:50.863281Z  INFO consensus: iroha_core::sumeragi::main_loop: View change updated addr=127.0.0.1:10000 role=Leader current_view_change_index=0
2023-11-27T07:45:52.864713Z  INFO consensus: iroha_core::sumeragi::main_loop: Creating block... addr=127.0.0.1:10000 txns=1
2023-11-27T07:45:52.866401Z  INFO consensus: iroha_core::sumeragi::main_loop: Committing block addr=127.0.0.1:10000 role=Leader block_height=2 block_hash=fd8645af6edacfe7d39d644ec82b047cc3d6b2830ee46482a16f44a4b0a6310d
2023-11-27T07:45:52.868815Z  INFO request{method=POST path=/query version=HTTP/1.1 remote.addr=127.0.0.1:53416}: warp::filters::trace: processing request
2023-11-27T07:45:52.868880Z  INFO request{method=POST path=/query version=HTTP/1.1 remote.addr=127.0.0.1:53416}:request{method=POST path=/query version=HTTP/1.1 remote.addr=127.0.0.1:53416}: warp::filters::trace: processing request
2023-11-27T07:45:52.869027Z  WARN request{method=POST path=/query version=HTTP/1.1 remote.addr=127.0.0.1:53416}:request{method=POST path=/query version=HTTP/1.1 remote.addr=127.0.0.1:53416}: warp::filters::trace: unable to serve request (client error) status=404 error=Some(Rejection(NotFound))
2023-11-27T07:45:52.872354Z  INFO consensus: iroha_core::sumeragi::main_loop: View change updated addr=127.0.0.1:10000 role=Leader current_view_change_index=0
2023-11-27T07:45:52.875677Z  INFO request{method=POST path=/query version=HTTP/1.1 remote.addr=127.0.0.1:53416}: warp::filters::trace: finished processing with success status=200
2023-11-27T07:45:52.876035Z  INFO test_network: Stopping peer p2p_addr=127.0.0.1:10000 api_addr=127.0.0.1:10001
2023-11-27T07:45:52.876071Z  INFO test_network: Shutting down peer...
2023-11-27T07:45:52.876418Z  INFO kura_receive_blocks_loop: iroha_core::kura: Kura block thread is being shut down. Writing remaining blocks to store.
2023-11-27T07:45:52.876450Z  INFO kura_receive_blocks_loop: iroha_core::kura: Kura has written remaining blocks to disk and is shutting down.
2023-11-27T07:45:52.877735Z  INFO consensus: iroha_core::sumeragi::main_loop: Sumeragi Thread is being shut down. reason=Ok(())
2023-11-27T07:45:52.880969Z  INFO iroha::samples: public_key=ed01207233BFC89DCBD68C19FDE6CE6158225298EC1131B6A130D1AEB454C1AB5183C0
2023-11-27T07:45:52.968359Z  INFO test-peer{p2p_addr=127.0.0.1:10000 api_addr=127.0.0.1:10001}:init:start{listen_addr=127.0.0.1:10000}: iroha_p2p::network: Network bound to listener
2023-11-27T07:45:53.196445Z  INFO test-peer{p2p_addr=127.0.0.1:10000 api_addr=127.0.0.1:10001}:init:kura_init: iroha_core::kura: Kura init complete mode=Strict block_count=3
2023-11-27T07:45:53.196555Z  WARN test-peer{p2p_addr=127.0.0.1:10000 api_addr=127.0.0.1:10001}:init: iroha: Failed to load wsv from snapshot, creating empty wsv error=Failed reading/writing "./storage/snapshot.data" from disk
2023-11-27T07:45:53.200044Z  WARN test-peer{p2p_addr=127.0.0.1:10000 api_addr=127.0.0.1:10001}:init: iroha: Telemetry not started
thread 'tokio-runtime-worker' panicked at 'Cannot block the current thread from within a runtime. This happens because a function attempted to block the current thread while the thread is being used to drive asynchronous tasks.', core/src/query/store.rs:232:14
2023-11-27T07:45:53.659350Z  INFO kura_receive_blocks_loop: iroha_core::kura: Kura block thread is being shut down. Writing remaining blocks to store.
2023-11-27T07:45:53.659417Z  INFO kura_receive_blocks_loop: iroha_core::kura: Kura has written remaining blocks to disk and is shutting down.
2023-11-27T07:45:53.661119Z  INFO iroha_core::query::store: All handler to LiveQueryStore are dropped. Shutting down...
thread 'integration::restart_peer::restarted_peer_should_have_the_same_asset_amount' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', core/test_network/src/lib.rs:447:43
2023-11-27T07:45:53.661236Z  INFO run{listen_addr=127.0.0.1:10000 public_key=ed0120DF2FDD69D02F41C1BB8AE01B5E4241ED008F3DB3E38919C59999FCA4C3AB7F96}: iroha_p2p::network: All handles to network actor are dropped. Shutting down...
2023-11-27T07:45:53.661811Z  INFO test_network: Stopping peer p2p_addr=127.0.0.1:10000 api_addr=127.0.0.1:10001
```

**Comment by ilchu** [comment]
Closing as that test was fixed. It was not about the query store, but the insufficient permissions for registering assets.
